openapi: 3.0.1
info:
  title: Swagger Playliststore
  description: 'This is a sample of Playliststore
  contact:
    email: mishagrygor.gmail.com
tags:
- name: song
  description: Everything about song
- name: playlist
  description: All about playlist
  